### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by skbolton** [jlgeering/tree-sitter-elixir#2]
More and more momentum’s happening to add tree sitter to neovim. This has peaked my interest in pushing forward elixir to have a tree sitter implementation. Your project seems the furthest along. What are your thoughts on picking up development and arching me up on where you left off?

**Comment by jlgeering** [comment]
I had some fun and learned a lot, but I'm not currently working on it anymore, nor do I plan to in the near future => @skbolton feel free to take over (not sure how ... fork and deprecate my repo?)

**Comment by skbolton** [comment]
Sounds good will do!

**Comment by jlgeering** [comment]
@skbolton tell me when you have something, I will link to your repo

**Comment by skbolton** [comment]
https://github.com/skbolton/tree-sitter-elixir
Next week I will move along with this

**Comment by jlgeering** [comment]
@skbolton updated the repo description
